[theme]
primaryColor = "#343c42ff"
backgroundColor = "#b39c74ff"
secondaryBackgroundColor = "#837466ff"
textColor = "#ffffff"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false